# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sentimeter',
                'doc_host': 'https://football-kowshik.github.io',
                'git_url': 'https://github.com/football-kowshik/sentimeter',
                'lib_path': 'sentimeter'},
  'syms': { 'sentimeter.utils': { 'sentimeter.utils.get_config': ('utils.html#get_config', 'sentimeter/utils.py'),
                                  'sentimeter.utils.get_data_directory': ('utils.html#get_data_directory', 'sentimeter/utils.py'),
                                  'sentimeter.utils.get_repo_directory': ('utils.html#get_repo_directory', 'sentimeter/utils.py')},
            'sentimeter.youtube': {},
            'sentimeter.youtube.channels': { 'sentimeter.youtube.channels.fetch_channel_details': ( 'youtube/channels.html#fetch_channel_details',
                                                                                                    'sentimeter/youtube/channels.py')},
            'sentimeter.youtube.utils': { 'sentimeter.youtube.utils.get_api_key': ( 'youtube/utils.html#get_api_key',
                                                                                    'sentimeter/youtube/utils.py'),
                                          'sentimeter.youtube.utils.get_resource': ( 'youtube/utils.html#get_resource',
                                                                                     'sentimeter/youtube/utils.py')}}}
