# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sentimeter',
                'doc_host': 'https://football-kowshik.github.io',
                'git_url': 'https://github.com/football-kowshik/sentimeter',
                'lib_path': 'sentimeter'},
  'syms': {'sentimeter.config': {}, 'sentimeter.core': {'sentimeter.core.foo': ('core.html#foo', 'sentimeter/core.py')}}}
