"""Configuration for `sentimeter`"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% auto 0
__all__ = ['YOUTUBE_API_KEY', 'GENAI_API_KEY', 'data_dir']

# %% ../nbs/00_config.ipynb 3
from pathlib import Path
import os, yaml
from dotenv import load_dotenv

# %% ../nbs/00_config.ipynb 4
#| eval: false
#| output: false
load_dotenv(dotenv_path="../.env")

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
if not YOUTUBE_API_KEY:
    raise ValueError("Missing YOUTUBE_API_KEY")

GENAI_API_KEY = os.getenv("GENAI_API_KEY")
if not GENAI_API_KEY:
    raise ValueError("Missing GENAI_API_KEY")

# %% ../nbs/00_config.ipynb 5
data_dir = Path("../data/")
os.makedirs(data_dir, exist_ok=True)

# %% ../nbs/00_config.ipynb 6
#| eval: false
#| output: false
with open("../config.yaml", "r") as f:
    config = yaml.safe_load(f)
