"""Setup required for running `sentimeter`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% auto 0
__all__ = ['load_config']

# %% ../nbs/00_config.ipynb 3
from pathlib import Path
import os
import yaml
import json
from dotenv import load_dotenv

# %% ../nbs/00_config.ipynb 14
def load_config(config_path):
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
    return config
