"""Setup required for running `sentimeter`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_config.ipynb 3
from pathlib import Path
import os
import yaml
import json
from dotenv import load_dotenv
