# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_utils.ipynb.

# %% auto 0
__all__ = ['get_repo_directory', 'get_data_directory', 'get_config']

# %% ../nbs/01_utils.ipynb 3
from pathlib import Path
import os
import yaml
import json

from nbdev.config import get_config
from dotenv import load_dotenv

# %% ../nbs/01_utils.ipynb 5
def get_repo_directory():
    cfg = get_config()
    project_root = Path(cfg.nbs_path).parent
    return project_root

# %% ../nbs/01_utils.ipynb 8
def get_data_directory():
    data_directory = get_repo_directory() / 'data'
    data_directory.mkdir(parents=True, exist_ok=True)
    return data_directory

# %% ../nbs/01_utils.ipynb 11
def get_config():
    config_path = "../config.yaml"
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
    return config
