# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_youtube.ipynb.

# %% auto 0
__all__ = ['fetch_channel_details']

# %% ../nbs/01_youtube.ipynb 3
from pathlib import Path
import os
import yaml
import json
from pathlib import Path

from googleapiclient.discovery import build
from .config import *

# %% ../nbs/01_youtube.ipynb 6
def fetch_channel_details(youtube, handle):
    response = youtube.channels().list(part="id", forHandle=handle.lstrip("@")).execute()
    return response
