# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/youtube/02_channels.ipynb.

# %% auto 0
__all__ = ['logger', 'fetch_channel_details', 'task_fetch_channel_details', 'extract_channel_id']

# %% ../../nbs/youtube/02_channels.ipynb 3
import json
from ..utils import *
from .utils import *

# %% ../../nbs/youtube/02_channels.ipynb 4
import logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

# %% ../../nbs/youtube/02_channels.ipynb 7
def fetch_channel_details(youtube, handle):
    response = youtube.channels().list(part="id", forHandle=handle.lstrip("@")).execute()
    return response

# %% ../../nbs/youtube/02_channels.ipynb 10
def task_fetch_channel_details():
    logger.info("Fetching channel details.")

    directory = data_directory / "youtube" / 'raw' / 'channels'
    directory.mkdir(parents=True, exist_ok=True)

    configs = read_config()
    youtube = get_resource()
    for channel in configs['youtube']['channels']:
        channel_details = fetch_channel_details(youtube, channel)
        with open(directory / f'{channel}.json', 'w') as f:
            json.dump(channel_details, f, indent = 4)

    logger.info(f"Channel details saved successfully.")

# %% ../../nbs/youtube/02_channels.ipynb 13
def extract_channel_id(details):
    return details['items'][0]['id']
