# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/youtube/02_channels.ipynb.

# %% auto 0
__all__ = ['fetch_channel_details', 'extract_channel_id']

# %% ../../nbs/youtube/02_channels.ipynb 3
import json
from .utils import *

# %% ../../nbs/youtube/02_channels.ipynb 5
def fetch_channel_details(handle):
    youtube = get_resource()
    response = youtube.channels().list(part="id", forHandle=handle.lstrip("@")).execute()
    return response

# %% ../../nbs/youtube/02_channels.ipynb 8
def extract_channel_id(details):
    return details['items'][0]['id']
