# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/youtube/02_channels.ipynb.

# %% auto 0
__all__ = ['fetch_channel_details']

# %% ../../nbs/youtube/02_channels.ipynb 4
import resource

def fetch_channel_details(handle):
    youtube = get_resource()
    print(youtube)
    return youtube
    response = youtube.channels().list(part="id", forHandle=handle.lstrip("@")).execute()
    return response
