# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/youtube/04_comments.ipynb.

# %% auto 0
__all__ = ['fetch_video_comments', 'extract_comment_texts']

# %% ../../nbs/youtube/04_comments.ipynb 3
import json
from .utils import *

# %% ../../nbs/youtube/04_comments.ipynb 5
def fetch_video_comments(video_id, max_comments=None):
    youtube = get_resource()
    
    comments = []
    next_page_token = None

    while True:
        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=100,
            textFormat="plainText",
            pageToken=next_page_token
        )
        response = request.execute()

        comments += response["items"]
        if max_comments and len(comments) >= max_comments:
            return comments[: max_comments]

        next_page_token = response.get("nextPageToken")
        if not next_page_token:
            break

    return comments

# %% ../../nbs/youtube/04_comments.ipynb 8
def extract_comment_texts(comments):
    texts = []
    for item in comments:
        text = item["snippet"]["topLevelComment"]["snippet"]["textDisplay"]
        texts.append(text)
    return texts
